import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { connectToDatabase } from "@/backend/lib/mongoose";
import { Inter } from "next/font/google";

await connectToDatabase(); // in production: should be called globally or dynamically on the server as static components aren't executed again

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased relative`}>
        <header className="min-h-[2.5vh] max-w-screen-sm mx-auto px-3 py-1 mb-8 border border-t-0 rounded-lg rounded-t-none">
          <Link className="hover:underline text-blue-500" href={"/"}>
            Home
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
